name: CI Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-11-arm

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          if (Test-Path build) {
            Remove-Item -Recurse -Force build
          }
          cmake -S . -B build -A ARM64
          cmake --build build --config Release

      - uses: actions/upload-artifact@v4
        with:
          name: PIFMS
          path: |
            build/PIFMSApp.exe
            build/PIFMSService.exe
